spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    listener:
      type: simple
      simple:
        default-requeue-rejected: false


# Optional: Hibernate settings for better startup performance
# hibernate:
#   ddl-auto: update
